"""init2

Revision ID: a60417ec863d
Revises: 117438e3458f
Create Date: 2026-02-16 21:35:42.780264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a60417ec863d'
down_revision: Union[str, Sequence[str], None] = '117438e3458f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oracle_cards',
    sa.Column('oracle_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('oracle_text', sa.Text(), nullable=True),
    sa.Column('type_line', sa.String(), nullable=True),
    sa.Column('power', sa.String(), nullable=True),
    sa.Column('toughness', sa.String(), nullable=True),
    sa.Column('color', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('cmc', sa.Float(), nullable=True),
    sa.Column('mana_cost', sa.String(), nullable=True),
    sa.Column('produced_mana', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('color_identity', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('loyalty', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('oracle_id', name=op.f('pk_oracle_cards')),
    sa.UniqueConstraint('oracle_id', name=op.f('uq_oracle_cards_oracle_id'))
    )
    op.create_table('sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('card_count', sa.Integer(), nullable=True),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.Column('set_type', sa.String(length=40), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sets')),
    sa.UniqueConstraint('code', name=op.f('uq_sets_code')),
    sa.UniqueConstraint('name', name=op.f('uq_sets_name'))
    )
    op.create_table('cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('oracle_id', sa.UUID(), nullable=False),
    sa.Column('collection_number', sa.String(), nullable=False),
    sa.Column('rarity', sa.String(), nullable=True),
    sa.Column('flavor_text', sa.Text(), nullable=True),
    sa.Column('set_id', sa.UUID(), nullable=False),
    sa.Column('artist', sa.String(), nullable=True),
    sa.Column('card_back_id', sa.UUID(), nullable=True),
    sa.Column('release_date', sa.DateTime(), nullable=False),
    sa.Column('layout', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['oracle_id'], ['oracle_cards.oracle_id'], name=op.f('fk_cards_oracle_id_oracle_cards')),
    sa.ForeignKeyConstraint(['set_id'], ['sets.id'], name=op.f('fk_cards_set_id_sets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cards')),
    sa.UniqueConstraint('collection_number', 'set_id', name=op.f('uq_cards_collection_number'))
    )
    op.create_table('card_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('size', sa.String(length=20), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name=op.f('fk_card_images_card_id_cards'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_card_images'))
    )
    op.create_index(op.f('ix_card_images_card_id'), 'card_images', ['card_id'], unique=False)
    op.create_foreign_key(op.f('fk_cube_cards_card_id_cards'), 'cube_cards', 'cards', ['card_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_cube_cards_card_id_cards'), 'cube_cards', type_='foreignkey')
    op.drop_index(op.f('ix_card_images_card_id'), table_name='card_images')
    op.drop_table('card_images')
    op.drop_table('cards')
    op.drop_table('sets')
    op.drop_table('oracle_cards')
    # ### end Alembic commands ###
