"""init

Revision ID: d87e0a3b6de6
Revises: 
Create Date: 2026-02-15 20:08:26.351551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd87e0a3b6de6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oracle_cards',
    sa.Column('oracle_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('oracle_text', sa.Text(), nullable=True),
    sa.Column('type_line', sa.String(), nullable=True),
    sa.Column('power', sa.String(), nullable=True),
    sa.Column('toughness', sa.String(), nullable=True),
    sa.Column('color', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('cmc', sa.Float(), nullable=True),
    sa.Column('mana_cost', sa.String(), nullable=True),
    sa.Column('produced_mana', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('color_identity', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('loyalty', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('oracle_id', name=op.f('pk_oracle_cards')),
    sa.UniqueConstraint('name', name=op.f('uq_oracle_cards_name'))
    )
    op.create_table('sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('card_count', sa.Integer(), nullable=True),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.Column('set_type', sa.String(length=40), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sets')),
    sa.UniqueConstraint('code', name=op.f('uq_sets_code')),
    sa.UniqueConstraint('name', name=op.f('uq_sets_name'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('image_file', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('oracle_id', sa.UUID(), nullable=False),
    sa.Column('collection_number', sa.String(), nullable=False),
    sa.Column('rarity', sa.String(), nullable=True),
    sa.Column('flavor_text', sa.Text(), nullable=True),
    sa.Column('set_id', sa.UUID(), nullable=False),
    sa.Column('artist', sa.String(), nullable=True),
    sa.Column('card_back_id', sa.UUID(), nullable=True),
    sa.Column('release_date', sa.DateTime(), nullable=False),
    sa.Column('layout', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['oracle_id'], ['oracle_cards.oracle_id'], name=op.f('fk_cards_oracle_id_oracle_cards')),
    sa.ForeignKeyConstraint(['set_id'], ['sets.id'], name=op.f('fk_cards_set_id_sets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cards')),
    sa.UniqueConstraint('collection_number', 'set_id', name=op.f('uq_cards_collection_number'))
    )
    op.create_table('cubes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cubename', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_cubes_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cubes'))
    )
    op.create_index(op.f('ix_cubes_id'), 'cubes', ['id'], unique=False)
    op.create_index(op.f('ix_cubes_user_id'), 'cubes', ['user_id'], unique=False)
    op.create_table('card_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('size', sa.String(length=20), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name=op.f('fk_card_images_card_id_cards'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_card_images'))
    )
    op.create_index(op.f('ix_card_images_card_id'), 'card_images', ['card_id'], unique=False)
    op.create_table('cube_cards',
    sa.Column('cube_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name=op.f('fk_cube_cards_card_id_cards'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cube_id'], ['cubes.id'], name=op.f('fk_cube_cards_cube_id_cubes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cube_id', 'card_id', name=op.f('pk_cube_cards'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cube_cards')
    op.drop_index(op.f('ix_card_images_card_id'), table_name='card_images')
    op.drop_table('card_images')
    op.drop_index(op.f('ix_cubes_user_id'), table_name='cubes')
    op.drop_index(op.f('ix_cubes_id'), table_name='cubes')
    op.drop_table('cubes')
    op.drop_table('cards')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('sets')
    op.drop_table('oracle_cards')
    # ### end Alembic commands ###
